/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package th2.h2;

import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author huyho
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        lblPath = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        txtKyTu = new javax.swing.JTextField();
        lblKyTu = new javax.swing.JLabel();
        btnFileChooserPath = new javax.swing.JButton();
        btnListFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFile = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPath.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPath.setText("Nhập đường dẫn");

        txtPath.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtKyTu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblKyTu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKyTu.setText("Lọc bỏ các file không chức ký tự");

        btnFileChooserPath.setBackground(java.awt.SystemColor.activeCaption);
        btnFileChooserPath.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFileChooserPath.setText("Chọn đường dẫn");
        btnFileChooserPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileChooserPathActionPerformed(evt);
            }
        });

        btnListFile.setBackground(java.awt.SystemColor.activeCaption);
        btnListFile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListFile.setText("Liệt kê danh sách file");
        btnListFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListFileActionPerformed(evt);
            }
        });

        listFile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(listFile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPath, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKyTu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtKyTu, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFileChooserPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPath)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblKyTu)
                        .addComponent(txtKyTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFileChooserPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListFile)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileChooserPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileChooserPathActionPerformed
        // fcPath mean is JFile Chooser Path
        // set up to show the path chossing dialog (Thiết lập hiển thị hộp thoại chọn đường dẫn)
        this.jFileChooser1.setVisible(true);
        // set up the mode to choose a file or a folder (thiết lập chế độ chọn tập tin hay thư mục)
        jFileChooser1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); // only choose the folder (directory)
        // for the dialog to show up (cho hộp thoại hiển thị lên)
        if(this.jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            // if the opening button is choosing
            try{
                txtPath.setText(jFileChooser1.getSelectedFile().getCanonicalPath());
            } catch(Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_btnFileChooserPathActionPerformed

    private void btnListFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListFileActionPerformed
        File dir = new File(txtPath.getText());
        File dsFile[] = dir.listFiles();
        String kytuloc = txtKyTu.getText();
        if (dsFile == null) {
            JOptionPane.showMessageDialog(null, "sai đường dẫn!");
        } else {
            try {
                DefaultListModel dm = new DefaultListModel();

                for (int i = 0; i < dsFile.length; i++) {
                    String fileName = dsFile[i].getName();
                    if(fileName.contains(kytuloc)){
                        dm.addElement(fileName);
                    }
                }
                listFile.setModel(dm);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.toString());
            }
        }
    }//GEN-LAST:event_btnListFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFileChooserPath;
    private javax.swing.JButton btnListFile;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKyTu;
    private javax.swing.JLabel lblPath;
    private javax.swing.JList<String> listFile;
    private javax.swing.JTextField txtKyTu;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}
