/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package th2_2;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author huyho
 */
public class TTFile extends javax.swing.JFrame {

    /**
     * Creates new form TTFile
     */
    public TTFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenTapTin = new javax.swing.JTextField();
        txtChuoi = new javax.swing.JTextField();
        txtNoiDungFile = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnDocNhiPhan = new javax.swing.JButton();
        btnGhiVanBan = new javax.swing.JButton();
        btnGhinhiphan = new javax.swing.JButton();
        btnDocVanBan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhập tên tập tin");

        jLabel2.setText("Nhập chuỗi");

        txtTenTapTin.setText("D:\\file.txt");

        txtChuoi.setText("12345678");

        jLabel3.setText("Nội dung file");

        btnDocNhiPhan.setText("Đọc file nhị phân");
        btnDocNhiPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocNhiPhanActionPerformed(evt);
            }
        });

        btnGhiVanBan.setText("Ghi file văn bản");
        btnGhiVanBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiVanBanActionPerformed(evt);
            }
        });

        btnGhinhiphan.setText("Ghi file nhị phân");
        btnGhinhiphan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhinhiphanActionPerformed(evt);
            }
        });

        btnDocVanBan.setText("Đọc file văn bản");
        btnDocVanBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocVanBanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoiDungFile, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenTapTin, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnDocVanBan))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnDocNhiPhan)))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGhiVanBan)
                            .addComponent(btnGhinhiphan))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtTenTapTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoiDungFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDocNhiPhan)
                    .addComponent(btnGhinhiphan))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDocVanBan)
                    .addComponent(btnGhiVanBan))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDocNhiPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocNhiPhanActionPerformed
        // TODO add your handling code here:
         byte a[];
        File file;
        try {
            file = new File(txtTenTapTin.getText());
            FileInputStream fi = new FileInputStream(file);
            a = new byte[fi.available()];
            fi.read(a);
            fi.close();
            // Xuất kết quả ra màn hình
            txtNoiDungFile.setText(new String(a));
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnDocNhiPhanActionPerformed

    private void btnGhinhiphanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhinhiphanActionPerformed
        // TODO add your handling code here:
        byte a[] = new byte[20];
        File file;
        int i;
        char s[] = txtChuoi.getText().toCharArray();
       
        for(i = 0; i < s.length; i++) {
            a[i] = (byte)s[i];
        }
        
        try {
            file = new File(txtTenTapTin.getText());
            FileOutputStream fo = new FileOutputStream(file);
            fo.write(a);
            JOptionPane.showMessageDialog(rootPane, "Ghi File Nhi Phan Thanh Cong");
            fo.close();
        } catch(IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGhinhiphanActionPerformed

    private void btnGhiVanBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiVanBanActionPerformed
        // TODO add your handling code here:
        try {
            FileWriter fw = new FileWriter(new File(txtTenTapTin.getText()));
            fw.write(txtChuoi.getText());
            fw.close();
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnGhiVanBanActionPerformed

    private void btnDocVanBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocVanBanActionPerformed
        // TODO add your handling code here:
         try {
            FileReader fr = new FileReader(new File(txtTenTapTin.getText()));
            StringBuffer sb = new StringBuffer();
            char ca[] = new char[5]; //đọc mỗi lần 5 ký tự
            while (fr.ready()) {
                int len = fr.read(ca);
                sb.append(ca, 0 , len);
            }
            fr.close();
            txtNoiDungFile.setText(sb + "");
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnDocVanBanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TTFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocNhiPhan;
    private javax.swing.JButton btnDocVanBan;
    private javax.swing.JButton btnGhiVanBan;
    private javax.swing.JButton btnGhinhiphan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtChuoi;
    private javax.swing.JTextField txtNoiDungFile;
    private javax.swing.JTextField txtTenTapTin;
    // End of variables declaration//GEN-END:variables
}
